// lib/dashboard/mockData.ts

import {
  TechGoal,
  TrackedTechnology,
  AIInsight,
  PriceData,
  TimelineEvent,
  SanctionAlert,
  Supplier,
  LogisticsWindow,
  UserStats,
  HotTopic,
  Expert,
  AISummaryData,
} from './types';

// === ТЕХНОЛОГ ===

export const mockGoals: TechGoal[] = [
  {
    id: '1',
    title: 'Снижение коксования',
    description: 'Печь E-101. Поиск методов снижения коксообразования в змеевиках',
    technologies: ['CFD-моделирование', 'Антикоксовые покрытия', 'Оптимизация режимов'],
    sourceTypes: ['journals', 'patents', 'cases'],
    notificationFrequency: 'immediate',
    status: 'active',
    newMaterials: 2,
    relevance: 94,
    lastUpdate: '3 часа назад',
    createdAt: '2025-12-15T10:00:00Z',
    updatedAt: '2026-01-29T14:30:00Z',
  },
  {
    id: '2',
    title: 'Катализатор риформинга',
    description: 'Повышение октанового числа. Исследование новых Pt-Re и Pt-Sn катализаторов',
    technologies: ['Pt-Re катализаторы', 'Pt-Sn катализаторы', 'Регенерация'],
    sourceTypes: ['journals', 'patents'],
    notificationFrequency: 'daily',
    status: 'active',
    newMaterials: 0,
    relevance: 96,
    lastUpdate: '1 день назад',
    createdAt: '2025-11-20T09:00:00Z',
    updatedAt: '2026-01-28T11:00:00Z',
  },
  {
    id: '3',
    title: 'Оптимизация ректификации',
    description: 'Колонна С-301. Повышение эффективности разделения',
    technologies: ['Тарелки', 'Насадки', 'APC'],
    sourceTypes: ['journals', 'cases'],
    notificationFrequency: 'weekly',
    status: 'paused',
    newMaterials: 0,
    relevance: 78,
    lastUpdate: '2 дня назад',
    createdAt: '2025-10-05T15:00:00Z',
    updatedAt: '2026-01-27T09:00:00Z',
  },
];

export const mockTrackedTechnologies: TrackedTechnology[] = [
  { id: '1', name: 'CFD-моделирование', publicationsPerMonth: 18, trend: 'up', changePercent: 45 },
  { id: '2', name: 'Дегидрирование пропана', publicationsPerMonth: 8, trend: 'stable', changePercent: 0 },
  { id: '3', name: 'Цифровые двойники', publicationsPerMonth: 22, trend: 'up', changePercent: 80 },
];

export const mockInsights: AIInsight[] = [
  {
    id: '1',
    title: 'Патент ExxonMobil: Селективный катализатор для риформинга',
    source: 'ExxonMobil',
    sourceType: 'patent',
    summary: 'Новый биметаллический Pt-Re катализатор с улучшенной селективностью к ароматическим соединениям.',
    keyPoints: [
      'Новый биметаллический Pt-Re катализатор',
      'Селективность к ароматике +12%',
      'Октановое число +3.5 пункта',
      'Срок службы катализатора увеличен до 4 лет',
    ],
    relevance: 'high',
    relevancePercent: 98,
    linkedGoalId: '2',
    linkedGoalTitle: 'Катализатор риформинга',
    date: '2026-01-29',
    tags: ['reforming', 'catalyst', 'Pt-Re', 'aromatics'],
  },
  {
    id: '2',
    title: 'Advanced CFD Modeling for Pyrolysis Furnaces',
    source: 'ACS Energy Letters',
    sourceType: 'article',
    summary: 'Исследователи из MIT разработали новую CFD-модель для прогнозирования коксообразования в трубах печи. Точность прогноза +40% по сравнению с Aspen HYSYS.',
    keyPoints: [
      'Новая CFD-модель MIT',
      'Точность прогноза +40%',
      'Интеграция с Aspen HYSYS',
      'Валидация на промышленных данных',
    ],
    relevance: 'high',
    relevancePercent: 94,
    linkedGoalId: '1',
    linkedGoalTitle: 'Снижение коксования',
    date: '2026-01-29',
    tags: ['CFD', 'pyrolysis', 'coking', 'modeling'],
  },
  {
    id: '3',
    title: 'Shell модернизировал установку в Сингапуре',
    source: 'Shell Press Release',
    sourceType: 'case',
    summary: 'Применение нового антикоксового покрытия TK-902 привело к снижению отложений на 65%. Срок окупаемости 1.2 года.',
    keyPoints: [
      'Покрытие TK-902',
      'Снижение отложений на 65%',
      'Payback: 1.2 года',
      'Установка в Сингапуре',
    ],
    relevance: 'medium',
    relevancePercent: 76,
    linkedGoalId: '1',
    linkedGoalTitle: 'Снижение коксования',
    date: '2026-01-28',
    tags: ['shell', 'coating', 'anti-coking', 'case-study'],
  },
  {
    id: '4',
    title: 'Новый подход к регенерации Pt катализаторов',
    source: 'Industrial & Engineering Chemistry Research',
    sourceType: 'article',
    summary: 'Разработан метод оксихлорирования для восстановления активности Pt катализаторов с эффективностью 95%.',
    keyPoints: [
      'Метод оксихлорирования',
      'Восстановление активности до 95%',
      'Снижение затрат на 30%',
    ],
    relevance: 'medium',
    relevancePercent: 72,
    linkedGoalId: '2',
    linkedGoalTitle: 'Катализатор риформинга',
    date: '2026-01-27',
    tags: ['catalyst', 'regeneration', 'platinum'],
  },
  {
    id: '5',
    title: 'AI-driven Distillation Column Optimization',
    source: 'AIChE 2025 Conference',
    sourceType: 'conference',
    summary: 'Применение машинного обучения для оптимизации ректификационных колонн показало снижение энергопотребления на 12%.',
    keyPoints: [
      'Machine Learning подход',
      'Снижение энергопотребления на 12%',
      'Real-time оптимизация',
    ],
    relevance: 'low',
    relevancePercent: 45,
    linkedGoalId: '3',
    linkedGoalTitle: 'Оптимизация ректификации',
    date: '2026-01-25',
    tags: ['AI', 'distillation', 'optimization', 'ML'],
  },
];

export const mockUserStats: UserStats = {
  materialsRead: 23,
  savedToBase: 8,
  searchQueries: 12,
  activeGoals: 3,
};

export const mockHotTopics: HotTopic[] = [
  { id: '1', name: 'Hydrogen Production', publications: 156 },
  { id: '2', name: 'Carbon Capture (CCUS)', publications: 134 },
  { id: '3', name: 'Digital Twin', publications: 98 },
];

export const mockExperts: Expert[] = [
  {
    id: '1',
    name: 'Dr. M. Adewale',
    company: 'UOP Honeywell',
    lastActivity: 'Доклад на AIChE 2025',
    activityType: 'conference',
  },
  {
    id: '2',
    name: 'Dr. Chen Kai',
    company: 'Sinopec R&D',
    lastActivity: 'Статья: Zeolite Catalysts',
    activityType: 'article',
  },
];

// === ЭКОНОМИСТ ===

export const mockPrices: PriceData[] = [
  {
    id: '1',
    name: 'ПНД ПП',
    code: 'PND_PP',
    currentPrice: 128500,
    previousPrice: 123300,
    unit: '₽/т',
    change: 4.2,
    trend: 'up',
    history: [
      { date: '2026-01-23', value: 120000 },
      { date: '2026-01-24', value: 121500 },
      { date: '2026-01-25', value: 122800 },
      { date: '2026-01-26', value: 123300 },
      { date: '2026-01-27', value: 125000 },
      { date: '2026-01-28', value: 127200 },
      { date: '2026-01-29', value: 128500 },
    ],
  },
  {
    id: '2',
    name: 'ПП (РФ)',
    code: 'PP_RU',
    currentPrice: 119200,
    previousPrice: 114800,
    unit: '₽/т',
    change: 3.8,
    trend: 'up',
    history: [
      { date: '2026-01-23', value: 112000 },
      { date: '2026-01-24', value: 113200 },
      { date: '2026-01-25', value: 114000 },
      { date: '2026-01-26', value: 114800 },
      { date: '2026-01-27', value: 116500 },
      { date: '2026-01-28', value: 118000 },
      { date: '2026-01-29', value: 119200 },
    ],
  },
  {
    id: '3',
    name: 'BRENT',
    code: 'BRENT',
    currentPrice: 70.87,
    previousPrice: 61.36,
    unit: '$/барр.',
    change: 15.5,
    trend: 'up',
    history: [
      { date: '2026-01-23', value: 62.50 },
      { date: '2026-01-24', value: 64.20 },
      { date: '2026-01-25', value: 65.80 },
      { date: '2026-01-26', value: 67.30 },
      { date: '2026-01-27', value: 68.90 },
      { date: '2026-01-28', value: 70.10 },
      { date: '2026-01-29', value: 70.87 },
    ],
  },
  {
    id: '4',
    name: 'Логистика',
    code: 'LOGISTICS',
    currentPrice: 18,
    previousPrice: 14,
    unit: 'дней',
    change: 28.6,
    trend: 'up',
    history: [
      { date: '2026-01-23', value: 12 },
      { date: '2026-01-24', value: 13 },
      { date: '2026-01-25', value: 14 },
      { date: '2026-01-26', value: 15 },
      { date: '2026-01-27', value: 16 },
      { date: '2026-01-28', value: 17 },
      { date: '2026-01-29', value: 18 },
    ],
  },
];

export const mockEvents: TimelineEvent[] = [
  {
    id: '1',
    title: 'Авария в ЮВА',
    description: 'Взрыв на заводе PTT Global Chemical в Таиланде привел к остановке производства ПП.',
    date: '2026-01-16',
    type: 'market',
    impact: 'negative',
    priceEffect: '+2.1% ПП',
  },
  {
    id: '2',
    title: 'Новый пакет санкций',
    description: 'ЕС ввел ограничения на поставки полимерного оборудования. Дефицит запчастей для экструдеров.',
    date: '2026-01-20',
    type: 'sanction',
    impact: 'negative',
    priceEffect: 'Дефицит ПЭ',
  },
  {
    id: '3',
    title: 'Коллапс ЖД логистики',
    description: 'Сбой на Транссибе из-за аварии. Задержки поставок до 5 дней.',
    date: '2026-01-24',
    type: 'logistics',
    impact: 'negative',
    priceEffect: '+логистика',
  },
  {
    id: '4',
    title: 'Запуск нового производства СИБУР',
    description: 'Ввод в эксплуатацию новой линии ПНД мощностью 500 тыс. тонн/год.',
    date: '2026-01-26',
    type: 'market',
    impact: 'positive',
    priceEffect: 'Стабилизация',
  },
  {
    id: '5',
    title: 'Новые требования Ростехнадзора',
    description: 'Обновленные требования к безопасности НПЗ вступают в силу с марта.',
    date: '2026-01-28',
    type: 'regulation',
    impact: 'neutral',
  },
];

export const mockAISummary: AISummaryData = {
  date: '2026-01-29',
  summary: 'Рынок входит в фазу высокой волатильности. Сочетание технологических факторов в Азии и логистического кризиса создаёт дефицит спецмарок полимеров. Ожидается продолжение роста цен в краткосрочной перспективе.',
  recommendations: [
    'Закупки: Контрактовать февральские объемы немедленно',
    'Логистика: Переориентация на автотранспорт',
    'Риски: Коррекция вниз возможна в середине марта',
  ],
};

// === ЗАКУПЩИК ===

export const mockSanctions: SanctionAlert[] = [
  {
    id: '1',
    supplier: 'Linde Engineering',
    country: 'Германия',
    riskLevel: 'critical',
    listType: 'SDN List (США)',
    description: 'Ограничение новых контрактов. Существующие заказы под угрозой.',
    affectedOrders: ['АВ-2024-045', 'АВ-2024-078'],
    alternatives: ['Alfa Laval', 'SMPCO', 'Jiangsu Zhenxing'],
    date: '2026-01-29',
  },
  {
    id: '2',
    supplier: 'Pt/Re катализаторы (ЕС)',
    country: 'ЕС',
    riskLevel: 'medium',
    listType: 'Экспортные ограничения ЕС',
    description: 'Новые ограничения на экспорт Pt/Re катализаторов. Активные заказы не затронуты.',
    affectedOrders: [],
    alternatives: ['Sinopec', 'CNPC'],
    date: '2026-01-28',
  },
  {
    id: '3',
    supplier: 'Baker Hughes',
    country: 'США',
    riskLevel: 'high',
    listType: 'Секторальные санкции',
    description: 'Ограничения на сервисное обслуживание турбокомпрессоров.',
    affectedOrders: ['СО-2025-012'],
    alternatives: ['Казанькомпрессормаш', 'REP Holding'],
    date: '2026-01-25',
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Alfa Laval',
    country: 'Швеция → Китай',
    countryFlag: '🇸🇪',
    products: ['Теплообменники', 'Сепараторы'],
    rating: 4.5,
    leadTime: '+3 месяца',
    notes: 'Дружественная юрисдикция. 15+ проектов в нефтехимии.',
    isSanctioned: false,
    isAlternative: true,
    jurisdictionStatus: 'friendly',
  },
  {
    id: '2',
    name: 'SMPCO',
    country: 'Иран',
    countryFlag: '🇮🇷',
    products: ['Теплообменники', 'Емкости'],
    rating: 3.8,
    leadTime: '+4 месяца',
    notes: 'Активно работает с РФ. 8 проектов в России. Риск задержек логистики.',
    isSanctioned: false,
    isAlternative: true,
    jurisdictionStatus: 'friendly',
  },
  {
    id: '3',
    name: 'Jiangsu Zhenxing',
    country: 'Китай',
    countryFlag: '🇨🇳',
    products: ['Теплообменники', 'Колонны'],
    rating: 3.5,
    leadTime: '+2 месяца',
    priceAdvantage: '-20-30% vs Linde',
    notes: 'Требуется верификация качества.',
    isSanctioned: false,
    isAlternative: true,
    jurisdictionStatus: 'friendly',
  },
  {
    id: '4',
    name: 'Sinopec Catalyst',
    country: 'Китай',
    countryFlag: '🇨🇳',
    products: ['Pt катализаторы', 'Re катализаторы', 'Цеолиты'],
    rating: 4.2,
    leadTime: '+1 месяц',
    notes: 'Альтернатива европейским поставщикам катализаторов.',
    isSanctioned: false,
    isAlternative: true,
    jurisdictionStatus: 'friendly',
  },
  {
    id: '5',
    name: 'Казанькомпрессормаш',
    country: 'Россия',
    countryFlag: '🇷🇺',
    products: ['Компрессоры', 'Турбодетандеры'],
    rating: 4.0,
    leadTime: 'Стандартный',
    notes: 'Локальный производитель. Полный цикл сервиса.',
    isSanctioned: false,
    isAlternative: true,
    jurisdictionStatus: 'friendly',
  },
];

export const mockLogistics: LogisticsWindow[] = [
  {
    id: '1',
    route: 'Европа → РФ (через Казахстан)',
    carrier: 'Multimodal',
    availability: 'open',
    transitTime: '18-22 дня',
  },
  {
    id: '2',
    route: 'Порт Новороссийск',
    carrier: 'Морской',
    availability: 'limited',
    transitTime: '+5 дней',
    delay: '+5 дней',
    reason: 'Погодные условия',
  },
  {
    id: '3',
    route: 'Транссиб',
    carrier: 'ЖД',
    availability: 'closed',
    transitTime: '-50% пропускной',
    reason: 'Авария на участке',
    alternatives: 'Автотранспорт, БАМ',
  },
];
